import type { InsertItem } from "@shared/schema";

export const GAME_ITEMS: InsertItem[] = [
  // WEAPONS
  {
    id: "plasma_pistol",
    name: "Plasma Pistol",
    description: "Standard issue sidearm with moderate damage output",
    slot: "weapon",
    rarity: "common",
    icon: "crosshair",
    statModifiers: { weaponStrength: 5, missileStrength: 3 },
    specialEffects: [],
    requiredLevel: 1,
    value: 50,
  },
  {
    id: "void_blade",
    name: "Void Blade",
    description: "Melee weapon infused with void energy",
    slot: "weapon",
    rarity: "uncommon",
    icon: "sword",
    statModifiers: { meleeAttack: 12, chargeBonus: 5 },
    specialEffects: ["void_damage"],
    requiredLevel: 3,
    value: 200,
  },
  {
    id: "quantum_rifle",
    name: "Quantum Rifle",
    description: "High-powered rifle that phases through armor",
    slot: "weapon",
    rarity: "rare",
    icon: "target",
    statModifiers: { missileStrength: 20, range: 50, accuracy: 10 },
    specialEffects: ["armor_pierce"],
    requiredLevel: 5,
    value: 500,
  },
  {
    id: "entropy_cannon",
    name: "Entropy Cannon",
    description: "Legendary weapon that destabilizes molecular bonds",
    slot: "weapon",
    rarity: "legendary",
    icon: "flame",
    statModifiers: { weaponStrength: 35, missileStrength: 25, chargeBonus: 15 },
    specialEffects: ["entropy_damage", "armor_pierce"],
    requiredLevel: 10,
    value: 2500,
  },

  // ARMOR
  {
    id: "standard_suit",
    name: "Standard Void Suit",
    description: "Basic protective suit for space operations",
    slot: "armor",
    rarity: "common",
    icon: "shield",
    statModifiers: { armour: 10, maxHealth: 10 },
    specialEffects: [],
    requiredLevel: 1,
    value: 75,
  },
  {
    id: "tactical_armor",
    name: "Tactical Combat Armor",
    description: "Military-grade armor with enhanced mobility",
    slot: "armor",
    rarity: "uncommon",
    icon: "shield",
    statModifiers: { armour: 25, meleeDefence: 8, speed: 5 },
    specialEffects: [],
    requiredLevel: 4,
    value: 350,
  },
  {
    id: "nanoweave_suit",
    name: "Nanoweave Exosuit",
    description: "Advanced suit with self-repairing nanobots",
    slot: "armor",
    rarity: "rare",
    icon: "shield",
    statModifiers: { armour: 40, maxHealth: 30, replenishmentRate: 3 },
    specialEffects: ["regeneration"],
    requiredLevel: 7,
    value: 800,
  },
  {
    id: "void_guardian",
    name: "Void Guardian Plate",
    description: "Legendary armor forged in the spaces between dimensions",
    slot: "armor",
    rarity: "legendary",
    icon: "shield",
    statModifiers: { armour: 60, maxHealth: 50, meleeDefence: 20, integrity: 10 },
    specialEffects: ["void_resistance", "regeneration"],
    requiredLevel: 12,
    value: 3000,
  },

  // HELMETS
  {
    id: "basic_helmet",
    name: "Basic Void Helm",
    description: "Standard helmet with basic HUD",
    slot: "helmet",
    rarity: "common",
    icon: "hard-hat",
    statModifiers: { armour: 5, accuracy: 3 },
    specialEffects: [],
    requiredLevel: 1,
    value: 40,
  },
  {
    id: "tactical_visor",
    name: "Tactical Targeting Visor",
    description: "Enhanced targeting systems for improved accuracy",
    slot: "helmet",
    rarity: "uncommon",
    icon: "eye",
    statModifiers: { accuracy: 15, range: 20 },
    specialEffects: ["targeting_assist"],
    requiredLevel: 3,
    value: 250,
  },
  {
    id: "neural_interface",
    name: "Neural Combat Interface",
    description: "Direct brain-computer link for faster reactions",
    slot: "helmet",
    rarity: "rare",
    icon: "brain",
    statModifiers: { accuracy: 20, clarity: 15, reloadTime: -2 },
    specialEffects: ["neural_link"],
    requiredLevel: 6,
    value: 600,
  },
  {
    id: "omniscient_crown",
    name: "Omniscient Crown",
    description: "Ancient artifact granting enhanced perception",
    slot: "helmet",
    rarity: "legendary",
    icon: "crown",
    statModifiers: { accuracy: 30, clarity: 25, leadership: 20 },
    specialEffects: ["precognition", "telepathy"],
    requiredLevel: 10,
    value: 2000,
  },

  // ACCESSORIES
  {
    id: "energy_cell",
    name: "Backup Energy Cell",
    description: "Auxiliary power source for extended operations",
    slot: "accessory",
    rarity: "common",
    icon: "battery",
    statModifiers: { maxEnergy: 20 },
    specialEffects: [],
    requiredLevel: 1,
    value: 30,
  },
  {
    id: "ammo_bandolier",
    name: "Ammo Bandolier",
    description: "Extra ammunition storage",
    slot: "accessory",
    rarity: "common",
    icon: "package",
    statModifiers: { maxAmmunition: 30 },
    specialEffects: [],
    requiredLevel: 1,
    value: 45,
  },
  {
    id: "diplomat_badge",
    name: "Diplomat's Badge",
    description: "Symbol of diplomatic authority recognized across factions",
    slot: "accessory",
    rarity: "uncommon",
    icon: "badge",
    statModifiers: { leadership: 10 },
    specialEffects: ["diplomatic_immunity"],
    requiredLevel: 2,
    value: 150,
  },
  {
    id: "void_crystal",
    name: "Void Crystal Pendant",
    description: "Crystallized void energy that enhances psionic abilities",
    slot: "accessory",
    rarity: "rare",
    icon: "gem",
    statModifiers: { clarity: 20, integrity: 10, maxEnergy: 30 },
    specialEffects: ["void_attunement"],
    requiredLevel: 5,
    value: 700,
  },
  {
    id: "temporal_anchor",
    name: "Temporal Anchor",
    description: "Stabilizes the wearer against time manipulation",
    slot: "accessory",
    rarity: "epic",
    icon: "anchor",
    statModifiers: { integrity: 15, speed: 10, replenishmentRate: 2 },
    specialEffects: ["time_resistance", "chrono_stability"],
    requiredLevel: 8,
    value: 1200,
  },

  // MODULES (stackable upgrades)
  {
    id: "speed_boost",
    name: "Speed Boost Module",
    description: "Enhances movement speed",
    slot: "module",
    rarity: "common",
    icon: "zap",
    statModifiers: { speed: 8 },
    specialEffects: [],
    requiredLevel: 1,
    value: 60,
  },
  {
    id: "damage_amp",
    name: "Damage Amplifier",
    description: "Increases weapon damage output",
    slot: "module",
    rarity: "uncommon",
    icon: "flame",
    statModifiers: { weaponStrength: 8, meleeAttack: 5 },
    specialEffects: [],
    requiredLevel: 3,
    value: 180,
  },
  {
    id: "shield_generator",
    name: "Personal Shield Generator",
    description: "Creates a protective energy barrier",
    slot: "module",
    rarity: "rare",
    icon: "shield",
    statModifiers: { armour: 15, meleeDefence: 10 },
    specialEffects: ["energy_shield"],
    requiredLevel: 5,
    value: 450,
  },

  // CONSUMABLES
  {
    id: "health_stim",
    name: "Health Stimulant",
    description: "Instantly restores 25 health",
    slot: "consumable",
    rarity: "common",
    icon: "heart",
    statModifiers: {},
    specialEffects: ["instant_heal_25"],
    requiredLevel: 1,
    value: 25,
  },
  {
    id: "energy_pack",
    name: "Energy Pack",
    description: "Restores 30 energy",
    slot: "consumable",
    rarity: "common",
    icon: "battery-charging",
    statModifiers: {},
    specialEffects: ["instant_energy_30"],
    requiredLevel: 1,
    value: 20,
  },
  {
    id: "integrity_restore",
    name: "Integrity Restoration Kit",
    description: "Restores 15 integrity",
    slot: "consumable",
    rarity: "uncommon",
    icon: "shield-check",
    statModifiers: {},
    specialEffects: ["restore_integrity_15"],
    requiredLevel: 2,
    value: 100,
  },
  {
    id: "corruption_purge",
    name: "Corruption Purge Serum",
    description: "Removes 20 cache corruption",
    slot: "consumable",
    rarity: "rare",
    icon: "refresh-cw",
    statModifiers: {},
    specialEffects: ["purge_corruption_20"],
    requiredLevel: 4,
    value: 300,
  },
];
