import type { InsertSkill } from "@shared/schema";

export const GAME_SKILLS: InsertSkill[] = [
  // COMBAT TREE (Red)
  {
    id: "combat_training",
    name: "Combat Training",
    description: "Basic combat fundamentals increase your attack power",
    category: "combat",
    tier: 1,
    icon: "swords",
    statModifiers: { meleeAttack: 5, weaponStrength: 5 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "armor_expertise",
    name: "Armor Expertise",
    description: "Learn to maximize your armor's protective capabilities",
    category: "combat",
    tier: 1,
    icon: "shield",
    statModifiers: { armour: 8, meleeDefence: 5 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "berserker_rage",
    name: "Berserker Rage",
    description: "Channel anger into devastating charge attacks",
    category: "combat",
    tier: 2,
    icon: "flame",
    statModifiers: { chargeBonus: 15, meleeAttack: 10 },
    prerequisites: ["combat_training"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "defensive_stance",
    name: "Defensive Stance",
    description: "Master defensive positioning to reduce incoming damage",
    category: "combat",
    tier: 2,
    icon: "shield-plus",
    statModifiers: { meleeDefence: 15, armour: 10 },
    prerequisites: ["armor_expertise"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "weapon_mastery",
    name: "Weapon Mastery",
    description: "Expert weapon handling increases all damage output",
    category: "combat",
    tier: 3,
    icon: "target",
    statModifiers: { weaponStrength: 20, missileStrength: 15, accuracy: 10 },
    prerequisites: ["berserker_rage"],
    cost: 3,
    maxRank: 1,
  },
  {
    id: "iron_will",
    name: "Iron Will",
    description: "Unbreakable resolve protects your integrity",
    category: "combat",
    tier: 3,
    icon: "brain",
    statModifiers: { integrity: 15, maxHealth: 25 },
    prerequisites: ["defensive_stance"],
    cost: 3,
    maxRank: 1,
  },

  // DIPLOMACY TREE (Blue)
  {
    id: "silver_tongue",
    name: "Silver Tongue",
    description: "Improve your negotiation abilities",
    category: "diplomacy",
    tier: 1,
    icon: "message-circle",
    statModifiers: { leadership: 8 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "cultural_insight",
    name: "Cultural Insight",
    description: "Better understanding of alien cultures improves relations",
    category: "diplomacy",
    tier: 1,
    icon: "book-open",
    statModifiers: { clarity: 8 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "master_negotiator",
    name: "Master Negotiator",
    description: "Your diplomatic skills are renowned across factions",
    category: "diplomacy",
    tier: 2,
    icon: "handshake",
    statModifiers: { leadership: 15 },
    prerequisites: ["silver_tongue"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "faction_diplomat",
    name: "Faction Diplomat",
    description: "Official recognition grants diplomatic advantages",
    category: "diplomacy",
    tier: 2,
    icon: "award",
    statModifiers: { clarity: 12, leadership: 8 },
    prerequisites: ["cultural_insight"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "galactic_ambassador",
    name: "Galactic Ambassador",
    description: "Your word carries weight across the galaxy",
    category: "diplomacy",
    tier: 3,
    icon: "crown",
    statModifiers: { leadership: 25, clarity: 15, integrity: 10 },
    prerequisites: ["master_negotiator", "faction_diplomat"],
    cost: 4,
    maxRank: 1,
  },

  // TECHNOLOGY TREE (Yellow)
  {
    id: "tech_savvy",
    name: "Tech Savvy",
    description: "Basic technical knowledge improves equipment effectiveness",
    category: "technology",
    tier: 1,
    icon: "cpu",
    statModifiers: { accuracy: 5, range: 10 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "efficient_systems",
    name: "Efficient Systems",
    description: "Optimize energy consumption and reload times",
    category: "technology",
    tier: 1,
    icon: "battery",
    statModifiers: { maxEnergy: 15, reloadTime: -1 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "targeting_systems",
    name: "Advanced Targeting",
    description: "Enhanced targeting computers improve hit chance",
    category: "technology",
    tier: 2,
    icon: "crosshair",
    statModifiers: { accuracy: 15, range: 25 },
    prerequisites: ["tech_savvy"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "power_management",
    name: "Power Management",
    description: "Superior energy efficiency across all systems",
    category: "technology",
    tier: 2,
    icon: "zap",
    statModifiers: { maxEnergy: 25, replenishmentRate: 3 },
    prerequisites: ["efficient_systems"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "quantum_computing",
    name: "Quantum Computing",
    description: "Harness quantum effects for unparalleled processing",
    category: "technology",
    tier: 3,
    icon: "atom",
    statModifiers: { accuracy: 20, reloadTime: -2, clarity: 10 },
    prerequisites: ["targeting_systems"],
    cost: 3,
    maxRank: 1,
  },

  // SURVIVAL TREE (Green)
  {
    id: "endurance",
    name: "Endurance Training",
    description: "Improve physical conditioning for extended operations",
    category: "survival",
    tier: 1,
    icon: "heart",
    statModifiers: { maxHealth: 15, replenishmentRate: 2 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "resource_efficiency",
    name: "Resource Efficiency",
    description: "Better resource management increases ammunition capacity",
    category: "survival",
    tier: 1,
    icon: "package",
    statModifiers: { maxAmmunition: 20 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "rapid_recovery",
    name: "Rapid Recovery",
    description: "Enhanced healing capabilities in the field",
    category: "survival",
    tier: 2,
    icon: "activity",
    statModifiers: { replenishmentRate: 5, maxHealth: 20 },
    prerequisites: ["endurance"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "combat_medic",
    name: "Combat Medic",
    description: "Apply medical knowledge in combat situations",
    category: "survival",
    tier: 2,
    icon: "plus-circle",
    statModifiers: { maxHealth: 30 },
    prerequisites: ["endurance"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "survivor",
    name: "Ultimate Survivor",
    description: "Nothing can keep you down for long",
    category: "survival",
    tier: 3,
    icon: "shield-check",
    statModifiers: { maxHealth: 50, replenishmentRate: 8, integrity: 10 },
    prerequisites: ["rapid_recovery", "combat_medic"],
    cost: 4,
    maxRank: 1,
  },

  // PSIONIC TREE (Purple)
  {
    id: "mental_fortitude",
    name: "Mental Fortitude",
    description: "Strengthen your mind against external influences",
    category: "psionic",
    tier: 1,
    icon: "brain",
    statModifiers: { clarity: 10, integrity: 5 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "void_attunement",
    name: "Void Attunement",
    description: "Develop sensitivity to void energies",
    category: "psionic",
    tier: 1,
    icon: "eye",
    statModifiers: { maxEnergy: 20 },
    prerequisites: [],
    cost: 1,
    maxRank: 3,
  },
  {
    id: "mind_shield",
    name: "Mind Shield",
    description: "Project a barrier protecting against mental attacks",
    category: "psionic",
    tier: 2,
    icon: "shield",
    statModifiers: { integrity: 15, clarity: 10 },
    prerequisites: ["mental_fortitude"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "void_channeling",
    name: "Void Channeling",
    description: "Draw power from the void between dimensions",
    category: "psionic",
    tier: 2,
    icon: "sparkles",
    statModifiers: { maxEnergy: 30, weaponStrength: 10 },
    prerequisites: ["void_attunement"],
    cost: 2,
    maxRank: 2,
  },
  {
    id: "transcendence",
    name: "Transcendence",
    description: "Achieve a higher state of consciousness",
    category: "psionic",
    tier: 3,
    icon: "sun",
    statModifiers: { clarity: 25, integrity: 20, maxEnergy: 40 },
    prerequisites: ["mind_shield", "void_channeling"],
    cost: 5,
    maxRank: 1,
  },
];
